### 使用urllib.error处理异常

`urllib.error`模块定义了由`urllib.request`产生的异常。如果出现了问题，`urllib.request`便会抛出`urllib.error`，下面会对其进行详细的介绍。

#### urllib.error.URLError

它继承自`OSError`，是`urllib.error`异常类的基类，由`urllib.request`产生的异常都可以通过捕获这个类来处理。

它具有一个属性`reason`，即返回错误的原因。

下面用一个实例来感受一下：

```python
# coding=utf-8
from urllib import request,error
try:
    response = request.urlopen('http://cuiqingcai.com/index.htm')
except error.URLError as e:
    print(e.reason)
```

我们打开一个不存在的页面，然后捕获了`URLError`这个异常。

运行结果：

```
Not Found
```

这样通过如上操作，避免了程序异常终止，同时异常得到了有效处理。

#### urllib.error.HTTPError

它是刚才介绍的`URLError`的子类，专门用来处理`HTTP`请求错误，比如认证请求失败等等。

它有三个属性。

`code`，返回`HTTP`状态码，比如404网页不存在，500服务器内部错误等等。

`reason`，同父类一样，返回错误的原因。

`headers`，返回`HTTP`响应头。

下面我们来用几个实例感受一下：

```python
# coding=utf-8
from urllib import request,error
try:
    response = request.urlopen('http://cuiqingcai.com/index.htm')
except error.HTTPError as e:
    print(e.reason, e.code, e.headers, seq='\n')
```
运行结果：

```
Not Found
404
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 03 Aug 2016 08:54:22 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Vary: Cookie
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Pragma: no-cache
Link: <http://cuiqingcai.com/wp-json/>; rel="https://api.w.org/"
```

依然是同样的网址，在这里我们捕获了`HTTPError`，输出了错误原因、错误代号、服务器响应头。

因为`URLError`是`HTTPError`的父类，所以我们可以先选择捕获子类的错误，再去捕获父类的错误，更好的写法如下：

```python
# coding=utf-8
from urllib import request, error

try:
    response = request.urlopen('http://cuiqingcai.com/index.htm')
except error.HTTPError as e:
    print(e.reason, e.code, e.headers, sep='\n')
except error.URLError as e:
    print(e.reason)
else:
    print('Request Successfully')
```

这样我们就可以做到先捕获`HTTPError`，获取它的错误码，错误原因，服务器响应头等详细信息。如果非`HTTPError`，再捕获`URLError`错误，输出错误原因。最后用`else`来处理正常的逻辑。

在有时候`e.reason`返回的不一定是字符串，可能是一个对象。

下面用一个实例来感受一下：

```python
# coding=utf-8
import socket
import urllib.request
import urllib.error

try:
    response = urllib.request.urlopen('https://www.baidu.com', timeout=0.01)
except urllib.error.URLError as e:
    print(type(e.reason))
    if isinstance(e.reason, socket.timeout):
        print('TIME OUT')
```
在这里我们直接设置了超时时间来强制抛出`timeout`异常。

运行结果如下： 

```python
<class 'socket.timeout'>
TIME OUT
```

可以发现`e,reason`的类型是`socket.timeout`。所以我们可以用`isinstance()`方法来判断它的类型，做出更详细的异常判断。

本节讲述了`urllib.error`的相关处理，通过合理地捕获异常可以做出更准确的异常判断，使得程序更佳稳健。
